Ensure the right version of netaddr as requirement
When pip installs netaddr-1.0.0 there following error shows:

   TemplateRuntimeError: No filter named 'ipwrap' found.

Force pip to install a previous version fixes the issue.

RHOSINFRA-5509

Change-Id: Iaa022a8e1fcff3c91e114eead66c87cf40798f05
(cherry picked from commit e4bd2d45ba79bd63c52ccc3f84d6ee0e1f15fdaa)