Fix PyGithub to 1.56
Need to fix PyGithub version to 1.56 to avoid the error below when
running 'infrared plugin add all' (seen with 2.1.0.post0):
~~~
AttributeError: type object 'Retry' has no attribute 'DEFAULT_ALLOWED_METHODS'
~~~￼

Tried with the latest versiont 2.1.1 (at the moment of this commit
is uploaded) but got this error:
~~~
infrared 2.0.1.dev5478 requires urllib3<1.25,>=1.21.1, but you have
urllib3 2.0.5 which is incompatible.
~~~￼

1.56 is the latest distribution found from gate.

Change-Id: Ie8af4a0e95876056db47f9ac42ed0bf1c40996b8