DNM squashed fixes 472302 + 527005
Ceph templates: support cephadm (for OSP>=17.0)

Some code paths have been adapted already, but those template files
need to refer to the cephadm environment files whenever needed
(i.e. when cephadm is used, from OSP 17.0).

ceph-rgw.yaml/docker-rgw.yml (same content, the latter should be removed)
don't need to be ported, as RGW is enabled by default, and in order to
disable it other changes are required.

ceph-mds.yaml's jinja template has been split into multiple lines
to prevent linting failures (line length).

This is a cherry-picked version of
https://review.gerrithub.io/c/redhat-openstack/infrared/+/527726
for testing purposes (stacking the commits).

- Change-Id: I0298373c5b80879b6680ca96d495872725d8d5b1

Create and append dvr override template for OSP <=14 only

Dvr override template should be generated only for OSP<=14 otherwise
OSP 17 deployment  with flag --network-dvr yes fails with error:
ValueError: environment has empty section "resource_registry"

- Change-Id: I60dee9c4e6bef6aaf1be9df5d94fc8da02eed73f

Change-Id: I0298373c5b80879b6680ca96d495872725d8d5b1