Revert "undercloud: no default for registry-mirror param"
This reverts commit 8ca0e5122a77fc058a5e18088d9db37ce7d88700.

Reason for revert: seems there are places where this param is referenced without '|default' or 'is defined' protection. Needs to be investigated since it did not affected the tripleo-undercloud gate job, but does phase1 in osp15 and 16. Re-proposed change will have to be more thoroughly tested with cherry-picking across releases.

2019-09-25 09:55:16.931 | 
2019-09-25 09:55:17.181 | TASK [template the undercloud.conf from local machine] *************************
2019-09-25 09:55:17.183 | task path: /home/rhos-ci/jenkins/workspace/phase1-15_director-rhel-8.0-virthost-1cont_1comp-ipv4-geneve-lvm/infrared/plugins/tripleo-undercloud/configure.yml:53
2019-09-25 09:55:17.185 | fatal: [undercloud-0]: FAILED! => {
2019-09-25 09:55:17.187 |     "changed": false
2019-09-25 09:55:17.189 | }
2019-09-25 09:55:17.192 | 
2019-09-25 09:55:17.193 | MSG:
2019-09-25 09:55:17.196 | 
2019-09-25 09:55:17.198 | AnsibleUndefinedVariable: 'dict object' has no attribute 'mirror'
2019-09-25 09:55:17.200 | 

Change-Id: I04061eecd49deb97b720a2781a37f1322a635ba8