Fix python-bugzilla error when running with py2
Currently on python2 IR fails with:
  ERROR: Failed building wheel for python-bugzilla                                                                                                                                                                             [19/692]
  Running setup.py clean for python-bugzilla
Successfully built infrared
Failed to build python-bugzilla
    Running setup.py install for python-bugzilla: started
    Running setup.py install for python-bugzilla: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/ospdeploy/ci/infrared/run/hab-01/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sdB07S/python-bugzilla/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sdB07S/python-bu
gzilla/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j7wBpn/install-record.txt --single-version-externally-managed --compile --install-headers /home/ospdeploy/ci/infrared/run/hab-01/venv/include/site/python2.7/python-bugzilla
         cwd: /tmp/pip-install-sdB07S/python-bugzilla/
    Complete output (27 lines):
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sdB07S/python-bugzilla/setup.py", line 147, in <module>
        "rpm": RPMCommand,
      File "/home/ospdeploy/ci/infrared/run/hab-01/venv/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/ospdeploy/ci/infrared/run/hab-01/venv/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-sdB07S/python-bugzilla/setup.py", line 103, in run
        self._make_man_pages()
      File "/tmp/pip-install-sdB07S/python-bugzilla/setup.py", line 82, in _make_man_pages
        rstbin = shutil.which("rst2man")
    AttributeError: 'module' object has no attribute 'which'

python-bugzilla 3.0.x which has been very recently released dropped py2
support, so let's pin in case we're on python2

Tested and it fixed my issue locally

Change-Id: I0f884d8371bda709e83138f909c0d853ca04e166