Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8214/ : Gate FAILED, you can retrigger tests with comment "recheck"

InvocationError: could not find executable ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8214/ )

No such file or directory ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8214/ )

command not found ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8214/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/3566/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck ovb" to retrigger only this test <<<
FAILURE: Introspect
>>>

Cancelling nested steps due to timeout ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/3566/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-composable-roles/3198/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck tripleo-composable-roles" to retrigger only this test <<<
FAILURE: Images
>>>

Cancelling nested steps due to timeout ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-composable-roles/3198/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud/3940/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck tripleo-overcloud" to retrigger only this test <<<
FAILURE: Images
>>>

Cancelling nested steps due to timeout ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud/3940/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud-osp14/1414/ : Gate ran successfully

Patch-set: 1
Tag: jenkins-gerrit-trigger
Reviewer: Gerrit User 1008131 <1008131@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1