Avoid idm client module conflict
The operation would result in switching of module 'idm' stream 'client' to stream 'DL1'
Error: It is not possible to switch enabled streams of a module.
It is recommended to ... reset the module using 'dnf module reset <module_name>' command

Change-Id: I2ee0c7caa71ec4bf19af30681c8d799527c07dec