Update patch set 10
Patch Set 10: Verified-1

Build Failed 

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8192/ : Gate FAILED, you can retrigger tests with comment "recheck"

InvocationError: could not find executable ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8192/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/3554/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck ovb" to retrigger only this test <<<
FAILURE: Introspect
>>>

Cancelling nested steps due to timeout ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/3554/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud/3925/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck tripleo-overcloud" to retrigger only this test <<<
FAILURE: Overcloud
>>>

Fatal ansible task ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud/3925/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-composable-roles/3186/ : Gate ran successfully

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud-osp14/1399/ : Gate ran successfully

Patch-set: 10
Tag: jenkins-gerrit-trigger
Reviewer: Gerrit User 1008131 <1008131@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1