Fix pyrsistent and py2.7
Due to the following issue:
https://github.com/tobgu/pyrsistent/issues/207

Infrared jobs with python 2.7 fail with:
Traceback (most recent call last):
  File "/tmp/ir-venv-0Z79U6x/bin/infrared", line 5, in <module>
    from infrared.main import main
  File "/tmp/ir-venv-0Z79U6x/lib/python2.7/site-packages/infrared/main.py", line 40, in <module>
    from infrared import api  # noqa
  File "/tmp/ir-venv-0Z79U6x/lib/python2.7/site-packages/infrared/api.py", line 10, in <module>
    from infrared.core.inspector.inspector import SpecParser
  File "/tmp/ir-venv-0Z79U6x/lib/python2.7/site-packages/infrared/core/inspector/inspector.py", line 7, in <module>
    from infrared.core.cli.cli import CliParser
  File "/tmp/ir-venv-0Z79U6x/lib/python2.7/site-packages/infrared/core/cli/cli.py", line 18, in <module>
    from infrared.core.services import CoreServices
  File "/tmp/ir-venv-0Z79U6x/lib/python2.7/site-packages/infrared/core/services/__init__.py", line 8, in <module>
    from infrared.core.services import ansible_config
  File "/tmp/ir-venv-0Z79U6x/lib/python2.7/site-packages/infrared/core/services/ansible_config.py", line 6, in <module>
    from infrared.core.utils.validators import AnsibleConfigValidator
  File "/tmp/ir-venv-0Z79U6x/lib/python2.7/site-packages/infrared/core/utils/validators.py", line 1, in <module>
    import jsonschema
  File "/tmp/ir-venv-0Z79U6x/lib/python2.7/site-packages/jsonschema/__init__.py", line 21, in <module>
    from jsonschema._types import TypeChecker
  File "/tmp/ir-venv-0Z79U6x/lib/python2.7/site-packages/jsonschema/_types.py", line 3, in <module>
    from pyrsistent import pmap
  File "/tmp/ir-venv-0Z79U6x/lib64/python2.7/site-packages/pyrsistent/__init__.py", line 3, in <module>
    from pyrsistent._pmap import pmap, m, PMap
  File "/tmp/ir-venv-0Z79U6x/lib64/python2.7/site-packages/pyrsistent/_pmap.py", line 98
    ) from e
         ^
SyntaxError: invalid syntax

Let's pin pyrsistent to 0.16.0 since 0.17.0 needs python3

Tested and fixes the issue for me.

Change-Id: I1d5686159e9afbc59e0e189e1f28fc11c4c9e16e