tox: recursive cleanup of __pycache__
Occasionally we can have 'tox -e py' tests failing in CI/gates
when doing preparation step of cleaning up pycache files/dirs.

It fails there as in CI these tests/envs are executed in parallel.
So some content may be present inside __pycache__ directories,
when 'py' env is running it's cleanup at same time when other test envs
are producing new .pyc files in these directories.

To prevent/minimize these issues there are multiple actions taken,
each of them decreases the chance of issues considerably:

- use one-pass-through of `find|xargs rm` approach (recursive rm will
  not have issue with non-empty dirs, and so makes `find .pyc` not
  needed too)
- scope this find-what-to-wipe only to __pycache__ (.pyc locations)
  which are involved in 'py' test env, ignoring any other ones
  (so ignore other testenv's .tox/<envdir> paths)
- use same PYTHONDONTWRITEBYTECODE in all testenv's so they do not
  even bother/attempt to write down __pycache__/.pyc files
  (it still produces some for few what seems python core-ish libs,
   so not 100%, but decreases it from ~44 thousand of pyc files to about
   10 - so drastically reducing possible problematic surface)
  (also from my tests seems there is no, or not noticeable speed impact)

Side-change: when modifying list of white-listed commands, i've sorted
it in alphabetical order.

Example output of such failing case (notice it's "py" tests failing on
"ansible-lint" tests pyc files):

  _________ output of py: _________
  py create: /home/rhos-ci/jenkins/workspace/gate-infrared-cloud-config-tox/infrared/.tox/py
  ...
  py run-test-pre: PYTHONHASHSEED='1424416524'
  py run-test: commands[0] | find . -type f -name '*.pyc' -delete
  py run-test: commands[1] | find . -type d -name __pycache__ -delete
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/inventory/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/parsing/utils/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/vars/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/executor/powershell/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/executor/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/plugins/action/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/playbook/__pycache__’: Directory not empty
  ERROR: InvocationError for command /usr/bin/find . -type d -name __pycache__ -delete (exited with code 1)

RHOSINFRA-4079

Change-Id: I01a6fca757bff8319c3db60746d42f0ff7f2385a