WIP : rally breaks on fstrings (prbably) since it runs on py2.7 on osp13
In this W/A we set the version to a prior non breaking rally version
that worked on py27

Error: f"Module `{target}` moved to `{new_module}` since Rally v{release}. "
                                                                        ^
SyntaxError: invalid syntax
Change-Id: I3c8a2087bb88495d7f639e9773ef1d911c790038