[Beaker][py3] Make Beaker module work on py3 environment
Beaker module doesn't work on python3, it crashes at core's http/client.py:

File "/usr/lib64/python3.6/http/client.py", line 979, in send
print(repr(data))
TypeError: a bytes-like object is required, not 'str'

since its output is hacked to obtain the Beaker's cookie. That is wrong
approach, also there are fundamental changes to string/byte handling
between py2/3. The simplest fix is to stop opening temp file as binary
tempfile.TemporaryFile(mode='w+b', ...) to 'w+', but that's not good
enough. Better remove the hack completely and replace with smth
more clean (overriding class method obtaining the value directly).

RHOSINFRA-3885

Change-Id: I5bdb640a30f1eab442231ff02f9eef5c104e8261