Update patch set 2
Patch Set 2: Verified+1

Build Unstable 

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/risk-12_update-rhel-7.4-virthost-1undercloud_3cont_2comp_3ceph-ssl/15/ : risk update test is unstable

Traceback (most recent call last):
testtools.testresult.real._StringException: Empty attachments:
  stderr
  stdout

pythonlogging:"": {{{
2018-02-06 13:33:26,009 32676 DEBUG    [tempest.scenario.manager] paths: img: /home/stack/tempest-dir/etc/cirros-0.3.1-x86_64-disk.img, container_format: bare, disk_format: qcow2, properties: None, ami: /home/stack/tempest-dir/etc/cirros-0.3.1-x86_64-blank.img, ari: /home/stack/tempest-dir/etc/cirros-0.3.1-x86_64-initrd, aki: /home/stack/tempest-dir/etc/cirros-0.3.1-x86_64-vmlinuz
2018-02-06 13:33:26,419 32676 INFO     [tempest.lib.common.rest_client] Request (TestMinimumBasicScenario:test_minimum_basic_scenario): 201 POST https://10.0.0.101:13292/v2/images 0.410s
2018-02-06 13:33:26,420 32676 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {"Content-Type": "application/json", "Accept": "application/json", "X-Auth-Token": "<omitted>"}
        Body: {"container_format": "bare", "disk_format": "qcow2", "name": "tempest-scenario-img--490127815", "visibility": "private"}
    Response - Headers: {"status": "201", u"content-length": "593", "content-location": "https://10.0.0.101:13292/v2/images", u"connection": "close", u"location": "https://10.0.0.101:13292/v2/images/ba8018f7-b980-428c-b76d-58970b4efa1c", u"date": "Tue, 06 Feb 2018 18:33:26 GMT", u"content-type": "application/json", u"x-openstack-request-id": "req-1a989578-adb1-4ae5-a212-a1f35299f41a"}
        Body: {"status": "queued", "name": "tempest-scenario-img--490127815", "tags": [], "container_format": "bare", "created_at": "2018-02-06T18:33:26Z", "size": null, "disk_format": "qcow2", "updated_at": "2018-02-06T18:33:26Z", "visibility": "private", "locations": [], "self": "/v2/images/ba8018f7-b980-428c-b76d-58970b4efa1c", "min_disk": 0, "protected": false, "id": "ba8018f7-b980-428c-b76d-58970b4efa1c", "file": "/v2/images/ba8018f7-b980-428c-b76d-58970b4efa1c/file", "checksum": null, "owner": "49b535d718ac45f0981c187973bb47c3", "virtual_size": null, "min_ram": 0, "schema": "/v2/schemas/image"}
2018-02-06 13:33:27,365 32676 INFO     [tempest.lib.common.rest_client] Request (TestMinimumBasicScenario:test_minimum_basic_scenario): 204 PUT https://10.0.0.101:13292/v2/images/ba8018f7-b980-428c-b76d-58970b4efa1c/file 0.944s
2018-02-06 13:33:27,365 32676 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {"Content-Type": "application/octet-stream", "X-Auth-Token": "<omitted>"}
        Body: <callable-iterator object at 0x4e6bdd0>
    Response - Headers: {"status": "204", u"content-length": "0", "content-location": "https://10.0.0.101:13292/v2/images/ba8018f7-b980-428c-b76d-58970b4efa1c/file", u"date": "Tue, 06 Feb 2018 18:33:27 GMT", u"content-type": "text/html; charset=UTF-8", u"connection": "close", u"x-openstack-request-id": "req-e5b22e52-3122-4ae7-b5a7-ec06e7c93a5c"}
        Body: 
2018-02-06 13:33:27,366 32676 DEBUG    [tempest.scenario.manager] image:ba8018f7-b980-428c-b76d-58970b4efa1c
2018-02-06 13:34:27,431 32676 WARNING  [urllib3.connectionpool] Retrying (Retry(total=9, connect=None, read=None, redirect=5)) after connection broken by "ReadTimeoutError("HTTPSConnectionPool(host="10.0.0.101", port=13774): Read timed out. (read timeout=60)",)": /v2.1/os-keypairs
2018-02-06 13:35:27,497 32676 WARNING  [urllib3.connectionpool] Retrying (Retry(total=8, connect=None, read=None, redirect=5)) after connection broken by "ReadTimeoutError("HTTPSConnectionPool(host="10.0.0.101", port=13774): Read timed out. (read timeout=60)",)": /v2.1/os-keypairs
2018-02-06 13:36:27,550 32676 WARNING  [urllib3.connectionpool] Retrying (Retry(total=7, connect=None, read=None, redirect=5)) after connection broken by "ReadTimeoutError("HTTPSConnectionPool(host="10.0.0.101", port=13774): Read timed out. (read timeout=60)",)": /v2.1/os-keypairs
2018-02-06 13:37:27,608 32676 WARNING  [urllib3.connectionpool] Retrying (Retry(total=6, connect=None, read=None, redirect=5)) after connection broken by "ReadTimeoutError("HTTPSConnectionPool(host="10.0.0.101", port=13774): Read timed out. (read timeout=60)",)": /v2.1/os-keypairs
2018-02-06 13:38:27,674 32676 WARNING  [urllib3.connectionpool] Retrying (Retry(total=5, connect=None, read=None, redirect=5)) after connection broken by "ReadTimeoutError("HTTPSConnectionPool(host="10.0.0.101", port=13774): Read timed out. (read timeout=60)",)": /v2.1/os-keypairs
2018-02-06 13:39:27,739 32676 WARNING  [urllib3.connectionpool] Retrying (Retry(total=4, connect=None, read=None, redirect=5)) after connection broken by "ReadTimeoutError("HTTPSConnectionPool(host="10.0.0.101", port=13774): Read timed out. (read timeout=60)",)": /v2.1/os-keypairs
2018-02-06 13:40:27,805 32676 WARNING  [urllib3.connectionpool] Retrying (Retry(total=3, connect=None, read=None, redirect=5)) after connection broken by "ReadTimeoutError("HTTPSConnectionPool(host="10.0.0.101", port=13774): Read timed out. (read timeout=60)",)": /v2.1/os-keypairs
2018-02-06 13:41:27,869 32676 WARNING  [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=5)) after connection broken by "ReadTimeoutError("HTTPSConnectionPool(host="10.0.0.101", port=13774): Read timed out. (read timeout=60)",)": /v2.1/os-keypairs
2018-02-06 13:41:46,677 32676 INFO     [tempest.lib.common.rest_client] Request (TestMinimumBasicScenario:_run_cleanups): 204 DELETE https://10.0.0.101:13292/v2/images/ba8018f7-b980-428c-b76d-58970b4efa1c 0.658s
2018-02-06 13:41:46,677 32676 DEBUG    [tempest.lib.common.rest_client] Request - Headers: {"Content-Type": "application/json", "Accept": "application/json", "X-Auth-Token": "<omitted>"}
        Body: None
    Response - Headers: {"status": "204", u"content-length": "0", "content-location": "https://10.0.0.101:13292/v2/images/ba8018f7-b980-428c-b76d-58970b4efa1c", u"date": "Tue, 06 Feb 2018 18:41:46 GMT", u"content-type": "text/html; charset=UTF-8", u"connection": "close", u"x-openstack-request-id": "req-52427797-c461-4b7c-bc30-8f90ba0cdce7"}
        Body:
}}}

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tempest/common/utils/__init__.py", line 89, in wrapper
    return f(self, *func_args, **func_kwargs)
  File "/usr/lib/python2.7/site-packages/tempest/scenario/test_minimum_basic.py", line 111, in test_minimum_basic_scenario
    keypair = self.create_keypair()
  File "/usr/lib/python2.7/site-packages/tempest/scenario/manager.py", line 110, in create_keypair
    body = client.create_keypair(name=name)
  File "/usr/lib/python2.7/site-packages/tempest/lib/services/compute/keypairs_client.py", line 70, in create_keypair
    resp, body = self.post("os-keypairs", body=post_body)
  File "/usr/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 279, in post
    return self.request("POST", url, extra_headers, headers, body, chunked)
  File "/usr/lib/python2.7/site-packages/tempest/lib/services/compute/base_compute_client.py", line 48, in request
    method, url, extra_headers, headers, body, chunked)
  File "/usr/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 653, in request
    body=body, chunked=chunked)
  File "/usr/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 549, in _request
    chunked=chunked
  File "/usr/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 582, in raw_request
    body=body, chunked=chunked)
  File "/usr/lib/python2.7/site-packages/tempest/lib/common/http.py", line 100, in request
    *args, **new_kwargs)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 73, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 248, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/ssl.py", line 759, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len or 1024)
  File "/usr/lib/python2.7/site-packages/fixtures/_fixtures/timeout.py", line 52, in signal_handler
    raise TimeoutException()
fixtures._fixtures.timeout.TimeoutException

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/risk-12_update-rhel-7.4-virthost-1undercloud_3cont_2comp_3ceph-ssl/15/ )

Patch-set: 2
Tag: jenkins-gerrit-trigger
Reviewer: rhosqeauto <1008131@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=+1