Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ospdui/88/ : Gate FAILED, you can retrigger tests with comment "recheck"

ERROR: Publisher �Publish JUnit test result report� failed: No test report files were found. Configuration error? ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ospdui/88/ )

source: filename argument required ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ospdui/88/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-12_packstack/142/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck packstack" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-12_packstack/142/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-7_packstack/145/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck packstack" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-7_packstack/145/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-10_packstack/143/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck packstack" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-10_packstack/143/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-openstack-ci-osp7/172/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck openstack-ci-osp7" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-openstack-ci-osp7/172/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-openstack/234/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck openstack" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-openstack/234/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-containers-minimal/768/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck containers-minimal" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-containers-minimal/768/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-virsh/314/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck virsh" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-virsh/314/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/1562/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck ovb" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/1562/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/4106/ : Gate ran successfully

Patch-set: 1
Tag: jenkins-gerrit-trigger
Reviewer: rhosqeauto <1008131@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1