DNM 527005 + 527832
Revert "'tripleo container image prepare' command to include custom env. files"

This reverts commit 402a6cf6c020dcae5770771579c2355bd5f6f905.

Based on the discussion on the original bug
https://bugzilla.redhat.com/show_bug.cgi?id=1629599
and a more recent bug:
https://bugzilla.redhat.com/show_bug.cgi?id=2024958
it looks like this patch is not really needed and it definitely introduces
breakages on OSP17 when certain environment files are used,
because they are not expected to be included.

The original issue, if still relevant, should be fixed by passing
the "custom roles + role counts", as hinted by
https://bugzilla.redhat.com/show_bug.cgi?id=2024958#c6

- Change-Id: I8aaaf98d9cec6b20fb9868e53241c2762855bee6

Create and append dvr override template for OSP <=14 only

Dvr override template should be generated only for OSP<=14 otherwise
OSP 17 deployment  with flag --network-dvr yes fails with error:
ValueError: environment has empty section "resource_registry"

- Change-Id: I60dee9c4e6bef6aaf1be9df5d94fc8da02eed73f

Change-Id: I0298373c5b80879b6680ca96d495872725d8d5b1