Update patch set 3
Patch Set 3: Verified-1

Build Failed 

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8252/ : Gate FAILED, you can retrigger tests with comment "recheck"

No such file or directory ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8252/ )

InvocationError: could not find executable ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8252/ )

command not found ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8252/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/3579/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck ovb" to retrigger only this test <<<
FAILURE: Provision
>>>

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/3579/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud/3960/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck tripleo-overcloud" to retrigger only this test <<<
FAILURE: Images
>>>

Cancelling nested steps due to timeout ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud/3960/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud-osp14/1434/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck tripleo-overcloud" to retrigger only this test <<<
FAILURE: Images
>>>

Cancelling nested steps due to timeout ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-overcloud-osp14/1434/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-composable-roles/3211/ : Gate ran successfully

Patch-set: 3
Tag: jenkins-gerrit-trigger
Reviewer: Gerrit User 1008131 <1008131@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1