Fix create openvswitch bridge and interfaces
The script templated in the ansible shell execution
task does not correctly render with proper line breaks
for each command when networks have multiple port groups.

Update the commands so that they never end with a '\'.
Prior to this fix the escaped line break before an actual
next command caused both commands to end up on one line,
which resulted in:

  Error: invalid <setting>.<property> 'nmcli'

Change-Id: I9686050c2fa677920bf18a3518781b2ed1c9bc51