Fixed groups['unused'] with defaults([])
Currentl the gate is failing with the error:
plugins/virsh/snapshot_quiesce.yml:200
Thursday 15 June 2023  02:25:40 +0000 (0:00:00.356)       0:01:19.596 *********
fatal: [undercloud-0 -> {{ item }}]: FAILED! => {}

 MSG:

 'dict object' has no attribute 'unused'

plugins/virsh/snapshot_quiesce.yml:200
Thursday 15 June 2023  02:25:40 +0000 (0:00:00.356)       0:01:19.596 *********
fatal: [undercloud-0 -> {{ item }}]: FAILED! => {}

 MSG:

 'dict object' has no attribute 'unused'

This patch uses difference(groups['unused'] | default([])) to have
some [] as a default value

Change-Id: I78c97f27629a6447dd2b306ed672008e6c8dd55f