WORK IN PROGRESS / DO NOT MERGE   ~~~~~~~~~~~ tox: recursive cleanup of __pycache__
WorkInProgress notes::     atm patch is just disabling cleanup and showing some debug info
- actual issue lies in aggressivity/blindness of this cleanup code VS parallel execution of tox targets in some of the CI jobs
- desired solution/fix/workaround need to be discussed and figured out first

Occasionally we can have tox tests failing
when doing preparation step of cleaning up pycache files/dirs.

It fails due to some content still being present inside __pycache__ directories,
and currently used find -delete approach cannot handle non-empty directories.
So for that lets use proper (print0 safe) find|xargs rm -rf approach.

Example output of such case:

  _________ output of py: _________
  py create: /home/rhos-ci/jenkins/workspace/gate-infrared-cloud-config-tox/infrared/.tox/py
  ...
  py run-test-pre: PYTHONHASHSEED='1424416524'
  py run-test: commands[0] | find . -type f -name '*.pyc' -delete
  py run-test: commands[1] | find . -type d -name __pycache__ -delete
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/inventory/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/parsing/utils/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/vars/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/executor/powershell/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/executor/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/plugins/action/__pycache__’: Directory not empty
  /usr/bin/find: cannot delete ‘./.tox/ansible-lint/lib/python3.6/site-packages/ansible/playbook/__pycache__’: Directory not empty
  ERROR: InvocationError for command /usr/bin/find . -type d -name __pycache__ -delete (exited with code 1)

RHOSINFRA-4079

Change-Id: I01a6fca757bff8319c3db60746d42f0ff7f2385a