argcomplete==1.12.1
bumping argcomplete.

conflicts run-test: commands[3] | python -m pip check
argcomplete 1.11.1 has requirement importlib-metadata<2,>=0.23; python_version == "3.6", but you have importlib-metadata 2.0.0.
ERROR: InvocationError for command /root/infrared/.tox/conflicts/bin/python -m pip check (exited with code 1)
plugin-registry recreate: /root/infrared/.tox/shared

Change-Id: I48fe8e9a7efb0a09a89989f4a33e7cf4524a0e8e