Fix undercloud backup when doing it locally.
When we don't provide any option to:

   ir tripleo-undercloud --snapshot-backup yes

which comes from the doc[1] we get an error:

    ASK [register md5 for the image on remote host] ********************************************************************************************************************************************************************
    fatal: [hypervisor]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'dest'\n\nThe error appears to have been in '/root/infrared/plugins/tripleo-undercloud/backup.yml': line 40, column 13, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n          - name: register md5 for the image on remote host\n            ^ here\n"}

    TASK [cleanup the undercloud image file] ****************************************************************************************************************************************************************************
    skipping: [hypervisor]

    TASK [cleanup in case of failure] ***********************************************************************************************************************************************************************************
    fatal: [hypervisor]: FAILED! => {"msg": "The conditional check 'local_hash.stdout != remote_hash.stdout' failed. The error was: error while evaluating conditional (local_hash.stdout != remote_hash.stdout): 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/root/infrared/plugins/tripleo-undercloud/backup.yml': line 57, column 13, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n          - name: cleanup in case of failure\n            ^ here\n"}

This is because install.dest is not defined.

This solve this by making sure that we avoid any code related to
remote backup when doing a local backup.

[1] https://infrared.readthedocs.io/en/stable/tripleo-undercloud.html#backup

Change-Id: I1705b327240ff8b14d16d293b913133b77176cd0