[uefi] add composable nodes into instackev profiles
It is questionable why these even have to be listed but for now
we just make sure it contains all the nodes needed to deploy
composable environment. Fixes error:
AnsibleUndefinedVariable: 'dict object' has no attribute 'database'

Change-Id: I3be9140e2e4288e8e46d19b4ed54207fa0c02e44