Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> I'm missing information in the commit message so asking here:
> this task " name: Install latest virtualenv using pip" is not required when running with OSP < 14? What is the error when running with OSP 13?

TASK [Install latest virtualenv using pip] *************************************
task path: /home/rhos-ci/jenkins/staging/workspace/DFG-osasinfra-shiftstack_on_vms-13_director-rhel-virthost-3cont_1comp_3ceph-ipv4-vxlan-hybrid_4.3_3master_3worker-ceph/infrared/plugins/tempest/tasks/setup/git/main.yml:33
Monday 27 April 2020 19:11:52 +0000 (0:00:00.073) 0:00:56.295 **********
fatal: [undercloud-0]: FAILED! =>
{ "changed": false, "cmd": [ "/bin/pip2", "install", "-U", "--force-reinstall", "virtualenv" ] }

MSG:

stdout: Collecting virtualenv
Downloading virtualenv-20.0.18-py2.py3-none-any.whl (4.6 MB)
Collecting distlib<1,>=0.3.0
Downloading distlib-0.3.0.zip (571 kB)
Collecting filelock<4,>=3.0.0
Downloading filelock-3.0.12.tar.gz (8.5 kB)
Collecting importlib-resources<2,>=1.0; python_version < "3.7"
Downloading importlib_resources-1.5.0-py2.py3-none-any.whl (21 kB)
Collecting six<2,>=1.9.0
Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"
Downloading pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting contextlib2<1,>=0.6.0; python_version < "3.3"
Downloading contextlib2-0.6.0.post1-py2.py3-none-any.whl (9.8 kB)
Collecting appdirs<2,>=1.4.3
Using cached appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
Collecting importlib-metadata<2,>=0.12; python_version < "3.8"
Downloading importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
Collecting zipp>=0.4; python_version < "3.8"
Downloading zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting singledispatch; python_version < "3.4"
Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl (12 kB)
Collecting typing; python_version < "3.5"
Downloading typing-3.7.4.1-py2-none-any.whl (26 kB)
Collecting scandir; python_version < "3.5"
Downloading scandir-1.10.0.tar.gz (33 kB)
Collecting configparser>=3.5; python_version < "3"
Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Building wheels for collected packages: distlib, filelock, scandir
Building wheel for distlib (setup.py): started
Building wheel for distlib (setup.py): finished with status 'done'
Created wheel for distlib: filename=distlib-0.3.0-py2-none-any.whl size=340428 sha256=15caa94539d68f8b5a4259e6aa84cc59c9740bd8df153f8bd6d9b36e621ad376
Stored in directory: /root/.cache/pip/wheels/0c/88/ac/41500883ea902d3409a83a827870a726346b5ebfd0523e91df
Building wheel for filelock (setup.py): started
Building wheel for filelock (setup.py): finished with status 'done'
Created wheel for filelock: filename=filelock-3.0.12-py2-none-any.whl size=7552 sha256=f406a11fcaeaaef35a6b613fd1a6f9fae5512146d98976a8cdbdb451c8f99e2e
Stored in directory: /root/.cache/pip/wheels/b9/91/23/b559c1f4fd55056712b3a71cd9cab1dc0089e2232d502ed72e
Building wheel for scandir (setup.py): started
Building wheel for scandir (setup.py): finished with status 'done'
Created wheel for scandir: filename=scandir-1.10.0-cp27-cp27mu-linux_x86_64.whl size=36079 sha256=26803d3af3c258a915e4c600fd232c9575e0101605275ca63cb867b330097da1
Stored in directory: /root/.cache/pip/wheels/58/2c/26/52406f7d1f19bcc47a6fbd1037a5f293492f5cf1d58c539edb
Successfully built distlib filelock scandir
Installing collected packages: distlib, filelock, contextlib2, zipp, six, singledispatch, scandir, pathlib2, configparser, importlib-metadata, typing, importlib-resources, appdirs, virtualenv
Attempting uninstall: contextlib2
Found existing installation: contextlib2 0.4.0

:stderr: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: tooz 1.60.2 requires msgpack>=0.4.0, which is not installed.
ERROR: heat-cfntools 1.3.0 requires argparse, which is not installed.
ERROR: tripleo-heat-templates 8.4.1 requires paunch>=1.0.0, which is not installed.
ERROR: glance-store 0.23.1.dev7 has requirement eventlet!=0.18.3,!=0.20.1,<0.21.0,>=0.18.2, but you'll have eventlet 0.20.1 which is incompatible.
ERROR: oslo-service 1.29.1 has requirement eventlet!=0.18.3,!=0.20.1,<0.21.0,>=0.18.2, but you'll have eventlet 0.20.1 which is incompatible.
ERROR: oslo-service 1.29.1 has requirement Paste>=2.0.2, but you'll have paste 1.7.5.1 which is incompatible.
ERROR: oslo-vmware 2.26.0 has requirement eventlet!=0.18.3,!=0.20.1,<0.21.0,>=0.18.2, but you'll have eventlet 0.20.1 which is incompatible.
ERROR: oslo-vmware 2.26.0 has requirement lxml!=3.7.0,>=3.4.1, but you'll have lxml 3.2.1 which is incompatible.
ERROR: os-brick 2.3.9 has requirement eventlet!=0.18.3,!=0.20.1,<0.21.0,>=0.18.2, but you'll have eventlet 0.20.1 which is incompatible.
ERROR: os-collect-config 8.3.1 has requirement eventlet!=0.18.3,!=0.20.1,<0.21.0,>=0.18.2, but you'll have eventlet 0.20.1 which is incompatible.
ERROR: os-collect-config 8.3.1 has requirement lxml!=3.7.0,>=3.4.1, but you'll have lxml 3.2.1 which is incompatible.
ERROR: python-tempestconf 0.0.0 has requirement PyYAML>=3.12, but you'll have pyyaml 3.10 which is incompatible.
ERROR: instack-undercloud 8.4.9 has requirement pystache>=0.5.4, but you'll have pystache 0.5.3 which is incompatible.
ERROR: os-net-config 8.5.1 has requirement pyudev>=0.16.1, but you'll have pyudev 0.15 which is incompatible.
ERROR: heat-cfntools 1.3.0 has requirement pbr!=0.7,<1.0,>=0.6, but you'll have pbr 3.1.1 which is incompatible.
ERROR: heat-cfntools 1.3.0 has requirement psutil<2.0.0,>=1.1.1, but you'll have psutil 5.2.2 which is incompatible.
ERROR: diskimage-builder 2.16.0 has requirement flake8<2.6.0,>=2.5.4, but you'll have flake8 2.4.1 which is incompatible.
ERROR: diskimage-builder 2.16.0 has requirement PyYAML>=3.12, but you'll have pyyaml 3.10 which is incompatible.
ERROR: os-apply-config 8.3.2 has requirement pystache>=0.5.4, but you'll have pystache 0.5.3 which is incompatible.
ERROR: Cannot uninstall 'contextlib2'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Patch-set: 4