Update patch set 11
Patch Set 11:

Build Failed 

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8237/ : Gate FAILED, you can retrigger tests with comment "recheck"

No such file or directory ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8237/ )

command not found ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8237/ )

InvocationError: could not find executable ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/8237/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-undercloud/1079/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck tripleo-undercloud" to retrigger only this test <<<
FAILURE: Images
>>>

Cancelling nested steps due to timeout ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tripleo-undercloud/1079/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/risk-14_director-rhel-7.6-virthost-1cont_1comp-ipv4-vxlan-containers/18/ : risk rocks test ran successfully

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/risk-14_director-rhel-7.6-virthost-3cont_2comp_3ceph-ipv4-vxlan-containers_HA/20/ : risk rocks test ran successfully

Patch-set: 11
Tag: jenkins-gerrit-trigger
Reviewer: Gerrit User 1008131 <1008131@d5d70762-12d0-45a1-890d-524b12d3f735>