Fix ansible.builtin.pause Module issue
When attempting to use 'ansible.builtin.pause' module as part of
an infrared plugin, the following error is raised:
TypeError: argument must be an int, or have a fileno() method.

The issue only affecting the ansible.builtin.pause because
only ansible.builtin.pause (ansible/plugins/action/pause.py) is
using curses.setupterm() method.
The curses.setupterm() Python method have optional argument named 'fd'
an if not supplied, the file descriptor for sys.stdout will be used.

The issue is that when running the ansible.builtin.pause without
Infrared, the sys.stdout is returing _io.TextIOWrapper and
oi.TextIOWrapper do have a method named 'fileno' that
return 1 (represent standard output),
but when running the ansible.builtin.pause within Infrared,
the sys.stdout is returing infrared.core.execute.IRStdoutFd and
infrared.core.execute.IRStdoutFd  don't have a
method named 'fileno'.

By adding a method named fileno to infrared.core.execute.IRStdoutFd
Class (that will return 1) ansible.builtin.pause will successfully run.

Change-Id: I20fbd79b035292c2913f3c070183722f56513546