Upgrade pip when a version is less or equal to 19
When we try to install the Octavia plugin we see the following:
ERROR: pyopenssl 22.1.0 has requirement cryptography<39,>=38.0.0, but you'll have cryptography 36.0.1 which is incompat
ible.
When upgrading to 21.3.1 it works as expected

Change-Id: I062192323613261056bae0c124957ef110032d56