Fix network agent check in snapshot_quiesce
Fixes network agent check by adding State==true to jq select query,
because for osp16+ returned values are diffrent than for osp13 and
osp10.

We also check for rc of the openstack request to catch api errors like
this one:
HttpException: 503: Server Error for url: https://overcloud.redhat.local:13696/v2.0/agents,
No server is available to handle this request.: 503 Service Unavailable

Change-Id: Ic96a180a69398b32ee9fee1ebdbe31436be81ba5