[vbmc][shade] Reinstall virtualenv when necessary
In python2 environments, sometimes the following error shows:

File "/usr/bin/virtualenv", line 6, in <module>
     from virtualenv import main
ImportError: cannot import name main

This is due to a corruption in the system's virtualenv/setuptools
installation. To resolve this, we force a reinstallation of the
package.

RHOSINFRA-3045

Change-Id: Id4986a0eaf6a136f0798066b59d263b4abe61267