Update patch set 6
Patch Set 6: Verified-1

Build Failed 

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/7871/ : Gate FAILED, you can retrigger tests with comment "recheck"

InvocationError: could not find executable ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/7871/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-virsh/840/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck virsh" to retrigger only this test <<<
FAILURE: Provision
>>>

missing rpm: python-libvirt ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-virsh/840/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-virsh-prefix/355/ : ABORTED <<<
FAILURE: Full cleanup
>>>

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-virsh-prefix/355/ )

Patch-set: 6
Tag: jenkins-gerrit-trigger
Reviewer: Gerrit User 1008131 <1008131@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1