Revert "Set root_device for ceph node explicitly"
This reverts commit 2288fafde6a77ba068cd79b85e50450ed4d53539.

This breaks RHOS-7 jobs:
ERROR: openstack Invalid command 'baremetal node set ceph-2 --property'

And there is option to override root disk for multinode systems:
  --root-disk-override ROOT-DISK-OVERRIDE
   This option allows to define custom root disk for multi-disk nodes
   The 'node' field supports 'controller' or 'controller-0' patterns.
   The 'hint' is property's name that helps to identify the root disk,
     e.g: serial, wwn
   The 'hintvalue' is a specific value for a hint's property, e.g: 123-asb-s1be
    Example:
     --root-disk-override node=controller,hint=size,hintvalue=50
     --root-disk-override node=compute-0,hint=name,hintvalue=/dev/sda
     --root-disk-override node=ceph,hint=rotational,hintvalue=false