Update patch set 1
Patch Set 1: Verified-1

Build Failed 

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-12_packstack/141/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck packstack" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-12_packstack/141/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-10_packstack/142/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck packstack" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-10_packstack/142/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-7_packstack/144/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck packstack" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-7_packstack/144/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-openstack-ci-osp7/171/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck openstack-ci-osp7" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-openstack-ci-osp7/171/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-openstack/233/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck openstack" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-openstack/233/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-containers-minimal/767/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck containers-minimal" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-containers-minimal/767/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/1561/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck ovb" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ovb/1561/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-virsh/313/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck virsh" to retrigger only this test

 ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-virsh/313/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ospdui/87/ : Gate FAILED, you can retrigger tests with comment "recheck"

ERROR: Publisher �Publish JUnit test result report� failed: No test report files were found. Configuration error? ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ospdui/87/ )

source: filename argument required ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-ospdui/87/ )

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-tox/4105/ : Gate ran successfully

Patch-set: 1
Tag: jenkins-gerrit-trigger
Reviewer: rhosqeauto <1008131@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1