[WIP] Wrap IPv6 address in CN in brackets
Attempt to solve SSL error:
  SSLError: CertificateError: hostname 'ipv6_addr' doesn't match '[ipv6_addr]'

Related rhbz#2010248

WIP - Because this is a guess, need to be tested.

Change-Id: I8b57833e10618888d0a36a4f3548f2f46a424ebd