[tempests] Gather facts from all nodes before updating inventory
The Change-Id: Ib4a76bf introduce an ability to set a tester node and
It updates inventory as first task with new tester node but this fails
on missing facts about other nodes so probably we should gather the facts
before updating the inventory.
Error: AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_user'

Change-Id: I4f6f87dc9486a203e975157fc2d0b45a6eb97fab