Unblock rally gate and use the latest stable  "pip>18.0"
pip==10 broke the rally gate with 'requests' not installing
pip==9 is buggy and old , see :
https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/\
job/gate-infrared-rally/88/consoleFull
and :
https://github.com/pypa/pip/issues/4059
error : 
SyntaxError: invalid syntax

  File "/usr/lib/python2.7/site-packages/pip-9.0.0-py2.7.egg/pip/\
  _vendor/html5lib/treewalkers/etree.py", line 13
    from pip._vendor. import string_types
                           ^
SyntaxError: invalid syntax

Change-Id: I72865b6a429cdf49b6c469ad245d427f5f06bb62